In [17]:
class ClassName:
#some functions and variables
#function--used to perform the specific activity
#Variables--data(memory)

In [8]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [13]:
class Demo:
    def test(self):
        print("test()for the class and method")
        return
obj=Demo()
obj.test()

test()for the class and method


In [18]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))

120


In [19]:
#Method
#def test(self,para1,para2)

In [22]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self,p1,p2):
        return p1+p2
        
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [24]:
# some inheritance
class person(object):
    #constructor
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
#Derived class
class employee(person):
     def isemployee(self):
        return True
    
emp=person("Anil")
print(emp.getname(),emp.isemployee())

emp1=employee("Ahkil")
print(emp1.getname(),emp1.isemployee())
    

Anil False
Ahkil True


### Python Numpy
#### numpy array is a bit like python list.
#### numpy array is a central data structure of the numpylib 
#### the lib actually short for "numeric python" or "numerical python"

In [29]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [7]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [34]:
lst=[1,2,3,4]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
int32


In [31]:
lst=[1.0,2.5,3.6,9.5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [33]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [35]:
# Re-shape the given array
# numpy.reshape(arrayname,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
#np.ones(shapes,dtype=float,order='c')
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [37]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [41]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [5 5 5 5]
 [1 1 1 1]]


In [42]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16    
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [44]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
# Indexing and slicing of Numpy
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print("first row:",a1[0])

first row: [1 2 3]


In [10]:
a1=np.array([(1,2,3),(4,5,6)])
print("second row:",a1[1])

second row: [4 5 6]


In [11]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column:",a1[:,1])

slicing column: [2 5]


In [12]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing last column:",a1[:,2])

slicing last column: [3 6]


In [13]:
a1=np.array([(1,2,3),(4,5,6)])
print("row and column:",a1[1,:1])

row and column: [4]


In [14]:
a1=np.random.normal(5,1,10)
print(a1)

[5.49172221 4.61633694 3.18690471 4.69639619 4.64995892 5.92721053
 6.66998905 5.35146973 6.74456691 4.79365859]


In [15]:
#a1=np.random.normal(5,1,10)
print(a1)
print("Min value=",np.min(a1))
print("Max value=",np.max(a1))
print("Mean value=",np.mean(a1))
print("Median value=",np.median(a1))

[4.41480964 2.75105211 5.57522885 4.67270896 4.26190975 4.28795256
 5.77351861 4.998798   4.66310809 4.62503253]
Min value= 2.7510521093201805
Max value= 5.773518605000782
Mean value= 4.6024119077048145
Median value= 4.644070308236647


In [2]:
import numpy as np
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [3]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [4]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

In [6]:
import numpy as np
a=np.array([1,2,3,5,8])
b=np.array([0,3,4,2,1])
c=a+b
c=c*a
print(c[2])

21


### Pandas Basics 

In [9]:
import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],
     "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
     "Mobilenumber":[999,888,777,888,777,999],
     "Adress":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  Mobilenumber Adress
0    Anil    anil@gmail.com           999    Hyd
1   Akhil   akhil@gmail.com           888    Hyd
2  Dinesh  dinesh@gmail.com           777    Hyd
3  Harsha  harsha@gmail.com           888    Hyd
4    Ajay    ajay@gmail.com           777    Hyd
5  Kranth  kranth@gmail.com           999    Hyd


In [11]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  Mobilenumber Adress
01    Anil    anil@gmail.com           999    Hyd
02   Akhil   akhil@gmail.com           888    Hyd
03  Dinesh  dinesh@gmail.com           777    Hyd
04  Harsha  harsha@gmail.com           888    Hyd
05    Ajay    ajay@gmail.com           777    Hyd
06  Kranth  kranth@gmail.com           999    Hyd


In [12]:
# supermaeket.csv - Analysis(Which product having higher % of selling)
# Which products having least selling %

In [ ]:
import pandas as pd
product_sellingData=pd.read_csv('Filename')